### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by camjac251** [7i/shorter#2]
I wanted to request a feature or maybe get your take on this as a feature. I've been looking for something in Go to replace the vast PHP file upload apps that replicate Dropbox or puush. Although in Go, the only scripts I've found are temporary uploaders or single user file managers.

Do you think it'd be possible to support a user authentication system with signing up and isolated root folders for each user's uploads?

**Comment by 7i** [comment]
Hi camjac251, sorry but that sounds like another project all together :) 
This project is a temporary url shortener and will include temporary files and temporary text blobs (like pastebin).
However one of the planed features is multiple logged in users that will be able to manage their links, text blobs and files so I guess that you could use it as stated in your request even if that is not the main purpose of the project (except for the sign up part). 
When the features are implemented you can just fork the repo and remove all (for you) unnecessary parts or just use it "as is".
Cheers!

**Comment by 7i** [comment]
Different design and purpose, shorter will be a simple url shortener.
